### ISSUE TITLE
Assistance needed for two issues on Uppmax. Couldn't reach you from elsewhere.

### ISSUE THREAD

**Issue by NauseaCantWrite** [richelbilderbeek/create_dnabert2_with_triton_singularity_container#3] opened 2024-09-10 18:54 UTC
I apologize for opening a thread in your git repo for something unrelated :(

I was not able to reach you via email... The same filter that keeps rejecting me from contacting uppmax support rejected me from writing an email to your address richel.bilderbeek@icm.uu.se (I tried reaching from multiple accounts and all were banned)... I also tried to reach you from X (formerly twitter)... I do not use that platform but I quickly created an account only to see that you have Direct Messages unavailable 😢 

Here is the email I tried to send: 

https://pastebin.com/arF9Us60

Password: G0tZu0fVhg

Here are the relevant files:

[singularity_build_dnabert2.txt](https://github.com/user-attachments/files/16949532/singularity_build_dnabert2.txt)
[NAISS_295686_conversation.txt](https://github.com/user-attachments/files/16949534/NAISS_295686_conversation.txt)

**Comment by richelbilderbeek** [comment] 2024-09-11 05:47
Hi @VladimirAlan97, no worries, I am happy you are so inventive :-)

Taking a look now :+1:

**Comment by richelbilderbeek** [comment] 2024-09-11 06:30
> 1. Regarding the usage of DNABert2 on uppmax (Trying to run on rackham without Triton).
> 
> I'm aware that you are actively working on implementing the whole thing (Triton included) on snowy and/or rackham. [...]
> 
> However, I wanted to try to run some things with the non-triton implementation that you provided here:
https://docs.uppmax.uu.se/software/dnabert2/
> 
> But I was not able to do so. Something weird must have happened because I could do it previously (when you first shared it with us, around 2 weeks ago I think). I deleted the image I built because we thought it was unnecessary (because of the new implementation with Triton) and because I wanted to edit it to install some libraries too.
>
> It says it has something to do with trying to build the wheel for a specific library (tokenizers), this was not a problem before. I attached the error message (the whole log, actually) to this email. Any guidance is appreciated.

I have a similar observation, of things not working anymore. I contacted the author of DNABERT2 by email and posted some [Issues](https://github.com/MAGICS-LAB/DNABERT_2/issues) for help. I feel if I fix my problem with Triton, it will also give the solution without Triton. 

I'll keep you posted! Sure, using this Issue for communication is fine :+1:

**Comment by richelbilderbeek** [comment] 2024-09-11 10:30
For reference, from my support colleagues regarding the bouncing:

(Moving this to the support-support queue, as it is about using
RT, not about using SUPR.)

For reference, tickets #297098, #297230, #297406, and #298811.

The rejection of the emails happen on the way in to UPPMAX, not
on the way from UPPMAX to the RT system. Specifically, it is the
spam filters that Sunet operate for Uppsala University that blocks
the messages.

When looking at the bounces that Alan linked to in RT #297230, I
see that it happens when the Microsoft and Gmail servers tries to
deliver the respective messages to the Sunet servers (the rejecting
server was mailfilter-ng-4.sunet.se, and the server that tried to
deliver to that server was SA1PR07MB10011.namprd07.prod.outlook.com
in the Microsoft case).

This is not something we can affect here at NSC. UPPMAX needs
to talk to Sunet about this (possibly while engaging the Uppsala
University central IT department).

**Comment by richelbilderbeek** [comment] 2024-09-11 12:42
About building without Triton: at [https://github.com/richelbilderbeek/create_dnabert2_singularity_container](https://github.com/richelbilderbeek/create_dnabert2_singularity_container) there is a reproducible build, that does seem to work, at least on GitHub Actions and on my local computer. What about we talk there?

**Comment by richelbilderbeek** [comment] 2024-09-11 12:43
I will close this Issue after a week of inactivity, i.e. after 2024-09-18

**Comment by richelbilderbeek** [comment] 2024-09-20 05:40
I've contacted SUNET with the email above.

Done!

**Closed as completed by richelbilderbeek** 2024-09-20 05:40 UTC

**Comment by NauseaCantWrite** [comment] 2024-09-21 00:11
Hi again Richel! I hadn't been able to post in this thread for 2 weeks due to some family and thesis-related issues. However rest assured that I've kept up with the emails from this thread and that Fede forwards.

We couldn't be more thankful for all the assistance you have provided. From enduring with us the pain that it is to follow the (deceivingly simple) installation process of DNABERT2 to helping our case reach SUNET staff to hopefully get our situation sorted soon :*]

- Regarding the usage of DNABERT2: Thanks for all the details on the experiments you ran to try and run it. I found very weird that the original singularity script that used to work (without Triton) stopped doing so all of a sudden... Nevertheless I appreciate your efforts and scripts so that we can properly use tritonless-DNABERT2 on Uppmax! and it seems doable in snowy too (without triton, of course)!  
Using Triton seems to be totally impossible to use, pity! 

- Regarding our email address being filtered out: It's a little bit scary that it is an issue that goes far beyond uppmax support. Thanks for contacting the appropriate staff so that it can be sorted. Fingers crossed!


PS: I stumbled upon your site and found it very interesting! I'll be taking a look onto some of your courses, they seem like excellent resources for a student like me!  Will also try to find a very thorough tutorial that let me understand containers from scratch (particularly singularity) do you have any suggestions? :P

Have a nice weekend! 

-Alan

**Comment by richelbilderbeek** [comment] 2024-09-24 17:13
Hi @VladimirAlan97, yup, the email situation is ... weird, indeed, fingers crossed! Happy to hear that DNABERT2 seems to be working good enough. Regarding Singularity, there is an UPPMAX course in it: https://pmitev.github.io/UPPMAX-Singularity-workshop/ :+1:
